name = "playjonny-casino-co-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-casino.co.at"
HMAC_KEY = "e722129a033997941e30c5f01098516a9516d05ee98bbf8f876aac1c462f1167"
COOKIE_NAME = "6zb"
PLAY_PATH = "try-now"
BUTTON_ID = "p15f3d2e0f404c5433ea189b0d58a1278"
GATE_SALT = "26915c7f998bece7"
