name = "playjonny-casino-co-at"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonny-casino.co.at"
HMAC_KEY = "e722129a033997941e30c5f01098516a9516d05ee98bbf8f876aac1c462f1167"
COOKIE_NAME = "jeg"
PLAY_PATH = "go"
BUTTON_ID = "p15f3d2e0f404c5433ea189b0d58a1278"
GATE_SALT = "15e8be1e84243d37"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "pumy"
CTA_SELECTOR = ".play-button"
